from faker import Faker

fake = Faker('de_DE')
print(fake.name())
print(' --- ')
print(fake.address())
print(' --- ')
print(fake.company())
print(' --- ')
print(fake.catch_phrase())
print(' --- ')
print(fake.profile())
print(' --- ')
print(fake.name())
print(fake.job())
print(fake.company())
print(fake.phone_number())
print(fake.text())
print(fake.street_name())
